name: thesis
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia/label/cuda-12.4.0

dependencies:
  #- python=3.12.0
  - python=3.11.9
  - pytorch
  - torchaudio
  - torchvision
  - pytorch-cuda
  - cudatoolkit
  - cudatoolkit-dev
  - cuda-nvcc
  - cuda-cudart-dev
  - gcc
  - gxx
  - faiss-gpu=1.8.0


  - pip:
    # github dependencies

    # project
    - ninja
    - yapf
    - -e registration-pipeline